# 預設設定值

DEFAULT_FORMAT = "mp3"
DEFAULT_QUALITY = "320"
DEFAULT_SLEEP = 10

DEFAULT_MIN_DURATION_MINUTES = 0     # 以分鐘為單位
DEFAULT_MAX_DURATION_MINUTES = 10

DEFAULT_PLATFORM = "YouTube"
DEFAULT_OUTPUT_DIR = "./downloads"
DEFAULT_REMOVE_NUMBER = True
DEFAULT_MAX_RESULTS = 3